# Generated by Django 3.1.1 on 2020-09-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_detail',
        ),
    ]
